a<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="AddDocs.aspx.cs" Inherits="UC_LIVE.AddDocs" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
	<div style="margin-right:20px; margin-top:10px; float:right;">
	<asp:Button ID="AddDocument" runat="server" Text="Add New Document" onclick="AddDocument_Click" />
	</div>
	
	<div style="width: 850px; margin-left: 20px; margin-top: 20px;">
		<cc1:TabContainer ID="DocumentsTab" runat="server" ActiveTabIndex="0" Width="920">
			<cc1:TabPanel runat="server" HeaderText="ClientDocs" ID="TabPanel1">
				<HeaderTemplate>Client Docs
				</HeaderTemplate>
				<ContentTemplate><asp:GridView ID="ClientDocuments" CssClass="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" CellPadding="1" DataKeyNames="DocID" DataSourceID="ClientsDataSource" EmptyDataText="There are no data records to display." ForeColor="#333333" GridLines="None" onselectedindexchanged="ClientDocuments_SelectedIndexChanged"><Columns><asp:CommandField ShowDeleteButton="True" ShowEditButton="True" ButtonType="Image" EditImageUrl="~/Images/Grid/IconEdit.png" DeleteImageUrl="~/Images/Grid/IconDelete.png" /><asp:BoundField DataField="DocID" HeaderText="ID" ReadOnly="True" SortExpression="DocID" /><asp:TemplateField HeaderText="Title" SortExpression="DocTitle"><EditItemTemplate><asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("DocTitle") %>'></asp:TextBox></EditItemTemplate><ItemTemplate><asp:HyperLink ID="ViewDocument" runat="server" NavigateUrl='<%# Eval("DocID", "ViewDocument.aspx?DocID={0}") %>' Text='<%# Eval("DocID") %>'></asp:HyperLink></ItemTemplate></asp:TemplateField><asp:BoundField DataField="DocStatus" HeaderText="Status" SortExpression="DocStatus" /><asp:BoundField DataField="DateCreated" HeaderText="Date Created" SortExpression="DateCreated" /><asp:BoundField DataField="DateUpdated" HeaderText="Date Updated" SortExpression="DateUpdated" /></Columns><EditRowStyle BackColor="#FDFDFD" /><FooterStyle CssClass="FooterStyle1" /><HeaderStyle CssClass="HeaderStyle1" /><PagerStyle CssClass="PagesStyle1" /><RowStyle BackColor="#EFF3FB" CssClass="RowStyle1" /><SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" /></asp:GridView><asp:SqlDataSource ID="ClientsDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [Documents] WHERE [DocID] = @DocID" InsertCommand="INSERT INTO [Documents] ([DocTitle], [DocBody], [DocLink], [DocStatus], [DateCreated], [DateUpdated]) VALUES (@DocTitle, @DocBody, @DocLink, @DocStatus, @DateCreated, @DateUpdated)" ProviderName="<%$ ConnectionStrings:UC_LIVE.Properties.Settings.ConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [Documents] , [ClaimDoc] where ClaimDoc.ContactTypeID=7
and Documents.DocID = ClaimDoc.DocID" UpdateCommand="UPDATE [Documents] SET [DocTitle] = @DocTitle, [DocBody] = @DocBody, [DocLink] = @DocLink, [DocStatus] = @DocStatus, [DateCreated] = @DateCreated, [DateUpdated] = @DateUpdated WHERE [DocID] = @DocID"><DeleteParameters><asp:Parameter Name="DocID" Type="Int32" /></DeleteParameters><InsertParameters><asp:Parameter Name="DocTitle" Type="String" /><asp:Parameter Name="DocBody" Type="String" /><asp:Parameter Name="DocLink" Type="String" /><asp:Parameter Name="DocStatus" Type="Int32" /><asp:Parameter Name="DateCreated" Type="DateTime" /><asp:Parameter Name="DateUpdated" Type="DateTime" /></InsertParameters><UpdateParameters><asp:Parameter Name="DocTitle" Type="String" /><asp:Parameter Name="DocBody" Type="String" /><asp:Parameter Name="DocLink" Type="String" /><asp:Parameter Name="DocStatus" Type="Int32" /><asp:Parameter Name="DateCreated" Type="DateTime" /><asp:Parameter Name="DateUpdated" Type="DateTime" /><asp:Parameter Name="DocID" Type="Int32" /></UpdateParameters></asp:SqlDataSource>
				</ContentTemplate>
			</cc1:TabPanel>
			<cc1:TabPanel runat="server" HeaderText="InsuranceDocs" ID="TabPanel2">
				<HeaderTemplate>Insurance Docs
				</HeaderTemplate>
				<ContentTemplate><asp:GridView ID="InsuranceDocs" CssClass="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" CellPadding="1" DataKeyNames="DocID" DataSourceID="InsuranceDataSource" EmptyDataText="There are no data records to display." ForeColor="#333333" GridLines="None"><RowStyle BackColor="#EFF3FB" CssClass="RowStyle1" /><Columns><asp:CommandField ShowDeleteButton="True" ShowEditButton="True" ButtonType="Image" EditImageUrl="~/Images/Grid/IconEdit.png" DeleteImageUrl="~/Images/Grid/IconDelete.png" /><asp:BoundField DataField="DocID" HeaderText="ID" ReadOnly="True" SortExpression="DocID" /><asp:TemplateField HeaderText="Title" SortExpression="DocTitle"><EditItemTemplate><asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("DocTitle") %>'></asp:TextBox></EditItemTemplate><ItemTemplate><asp:HyperLink ID="ViewDocument" runat="server" NavigateUrl='<%# Eval("DocID", "ViewDocument.aspx?DocID={0}") %>' Text='<%# Eval("DocID") %>'></asp:HyperLink></ItemTemplate></asp:TemplateField><asp:BoundField DataField="DocStatus" HeaderText="Status" SortExpression="DocStatus" /><asp:BoundField DataField="DateCreated" HeaderText="Date Created" SortExpression="DateCreated" /><asp:BoundField DataField="DateUpdated" HeaderText="Date Updated" SortExpression="DateUpdated" /></Columns><EditRowStyle BackColor="#FDFDFD" /><FooterStyle CssClass="FooterStyle1" /><HeaderStyle CssClass="HeaderStyle1" /><PagerStyle CssClass="PagesStyle1" /><SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" /></asp:GridView><asp:SqlDataSource ID="InsuranceDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [Documents] WHERE [DocID] = @DocID" InsertCommand="INSERT INTO [Documents] ([DocTitle], [DocBody], [DocLink], [DocStatus], [DateCreated], [DateUpdated]) VALUES (@DocTitle, @DocBody, @DocLink, @DocStatus, @DateCreated, @DateUpdated)" ProviderName="<%$ ConnectionStrings:UC_LIVE.Properties.Settings.ConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [Documents] , [ClaimDoc] where ClaimDoc.ContactTypeID=1
and Documents.DocID = ClaimDoc.DocID" UpdateCommand="UPDATE [Documents] SET [DocTitle] = @DocTitle, [DocBody] = @DocBody, [DocLink] = @DocLink, [DocStatus] = @DocStatus, [DateCreated] = @DateCreated, [DateUpdated] = @DateUpdated WHERE [DocID] = @DocID"><DeleteParameters><asp:Parameter Name="DocID" Type="Int32" /></DeleteParameters><InsertParameters><asp:Parameter Name="DocTitle" Type="String" /><asp:Parameter Name="DocBody" Type="String" /><asp:Parameter Name="DocLink" Type="String" /><asp:Parameter Name="DocStatus" Type="Int32" /><asp:Parameter Name="DateCreated" Type="DateTime" /><asp:Parameter Name="DateUpdated" Type="DateTime" /></InsertParameters><UpdateParameters><asp:Parameter Name="DocTitle" Type="String" /><asp:Parameter Name="DocBody" Type="String" /><asp:Parameter Name="DocLink" Type="String" /><asp:Parameter Name="DocStatus" Type="Int32" /><asp:Parameter Name="DateCreated" Type="DateTime" /><asp:Parameter Name="DateUpdated" Type="DateTime" /><asp:Parameter Name="DocID" Type="Int32" /></UpdateParameters></asp:SqlDataSource>
				</ContentTemplate>
			</cc1:TabPanel>
			</ContentTemplate></cc1:TabPanel>
			<cc1:TabPanel runat="server" HeaderText="EngineerDocs" ID="TabPanel3">
				<HeaderTemplate>Engineers Docs
				</HeaderTemplate>
				<ContentTemplate><asp:GridView ID="EngineerDocs" CssClass="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" CellPadding="1" DataKeyNames="DocID" DataSourceID="EngineerDataSource" EmptyDataText="There are no data records to display." ForeColor="#333333" GridLines="None"><RowStyle BackColor="#EFF3FB" CssClass="RowStyle1" /><Columns><asp:CommandField ShowDeleteButton="True" ShowEditButton="True" ButtonType="Image" EditImageUrl="~/Images/Grid/IconEdit.png" DeleteImageUrl="~/Images/Grid/IconDelete.png" /><asp:BoundField DataField="DocID" HeaderText="ID" ReadOnly="True" SortExpression="DocID" /><asp:TemplateField HeaderText="Title" SortExpression="DocTitle"><EditItemTemplate><asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("DocTitle") %>'></asp:TextBox></EditItemTemplate><ItemTemplate><asp:HyperLink ID="ViewDocument" runat="server" NavigateUrl='<%# Eval("DocID", "ViewDocument.aspx?DocID={0}") %>' Text='<%# Eval("DocID") %>'></asp:HyperLink></ItemTemplate></asp:TemplateField><asp:BoundField DataField="DocStatus" HeaderText="Status" SortExpression="DocStatus" /><asp:BoundField DataField="DateCreated" HeaderText="Date Created" SortExpression="DateCreated" /><asp:BoundField DataField="DateUpdated" HeaderText="Date Updated" SortExpression="DateUpdated" /></Columns><EditRowStyle BackColor="#FDFDFD" /><FooterStyle CssClass="FooterStyle1" /><HeaderStyle CssClass="HeaderStyle1" /><PagerStyle CssClass="PagesStyle1" /><SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" /></asp:GridView><asp:SqlDataSource ID="EngineerDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [Documents] WHERE [DocID] = @DocID" InsertCommand="INSERT INTO [Documents] ([DocTitle], [DocBody], [DocLink], [DocStatus], [DateCreated], [DateUpdated]) VALUES (@DocTitle, @DocBody, @DocLink, @DocStatus, @DateCreated, @DateUpdated)" ProviderName="<%$ ConnectionStrings:UC_LIVE.Properties.Settings.ConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [Documents] , [ClaimDoc] where ClaimDoc.ContactTypeID=3
and Documents.DocID = ClaimDoc.DocID" UpdateCommand="UPDATE [Documents] SET [DocTitle] = @DocTitle, [DocBody] = @DocBody, [DocLink] = @DocLink, [DocStatus] = @DocStatus, [DateCreated] = @DateCreated, [DateUpdated] = @DateUpdated WHERE [DocID] = @DocID"><DeleteParameters><asp:Parameter Name="DocID" Type="Int32" /></DeleteParameters><InsertParameters><asp:Parameter Name="DocTitle" Type="String" /><asp:Parameter Name="DocBody" Type="String" /><asp:Parameter Name="DocLink" Type="String" /><asp:Parameter Name="DocStatus" Type="Int32" /><asp:Parameter Name="DateCreated" Type="DateTime" /><asp:Parameter Name="DateUpdated" Type="DateTime" /></InsertParameters><UpdateParameters><asp:Parameter Name="DocTitle" Type="String" /><asp:Parameter Name="DocBody" Type="String" /><asp:Parameter Name="DocLink" Type="String" /><asp:Parameter Name="DocStatus" Type="Int32" /><asp:Parameter Name="DateCreated" Type="DateTime" /><asp:Parameter Name="DateUpdated" Type="DateTime" /><asp:Parameter Name="DocID" Type="Int32" /></UpdateParameters></asp:SqlDataSource>
				</ContentTemplate>
			</cc1:TabPanel>
			<cc1:TabPanel runat="server" HeaderText="SolicitorDocs" ID="TabPanel4">
				<HeaderTemplate>Solicitor Docs
				</HeaderTemplate>
				<ContentTemplate><asp:GridView ID="SolicitorDocs" CssClass="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" CellPadding="1" DataKeyNames="DocID" DataSourceID="SolicitorDataSource" EmptyDataText="There are no data records to display." ForeColor="#333333" GridLines="None"><RowStyle BackColor="#EFF3FB" CssClass="RowStyle1" /><Columns><asp:CommandField ShowDeleteButton="True" ShowEditButton="True" ButtonType="Image" EditImageUrl="~/Images/Grid/IconEdit.png" DeleteImageUrl="~/Images/Grid/IconDelete.png" /><asp:BoundField DataField="DocID" HeaderText="ID" ReadOnly="True" SortExpression="DocID" /><asp:TemplateField HeaderText="Title" SortExpression="DocTitle"><EditItemTemplate><asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("DocTitle") %>'></asp:TextBox></EditItemTemplate><ItemTemplate><asp:HyperLink ID="ViewDocument" runat="server" NavigateUrl='<%# Eval("DocID", "ViewDocument.aspx?DocID={0}") %>' Text='<%# Eval("DocID") %>'></asp:HyperLink></ItemTemplate></asp:TemplateField><asp:BoundField DataField="DocStatus" HeaderText="Status" SortExpression="DocStatus" /><asp:BoundField DataField="DateCreated" HeaderText="Date Created" SortExpression="DateCreated" /><asp:BoundField DataField="DateUpdated" HeaderText="Date Updated" SortExpression="DateUpdated" /></Columns><EditRowStyle BackColor="#FDFDFD" /><FooterStyle CssClass="FooterStyle1" /><HeaderStyle CssClass="HeaderStyle1" /><PagerStyle CssClass="PagesStyle1" /><SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" /></asp:GridView><asp:SqlDataSource ID="SolicitorDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [Documents] WHERE [DocID] = @DocID" InsertCommand="INSERT INTO [Documents] ([DocTitle], [DocBody], [DocLink], [DocStatus], [DateCreated], [DateUpdated]) VALUES (@DocTitle, @DocBody, @DocLink, @DocStatus, @DateCreated, @DateUpdated)" ProviderName="<%$ ConnectionStrings:UC_LIVE.Properties.Settings.ConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [Documents] , [ClaimDoc] where ClaimDoc.ContactTypeID=2
and Documents.DocID = ClaimDoc.DocID" UpdateCommand="UPDATE [Documents] SET [DocTitle] = @DocTitle, [DocBody] = @DocBody, [DocLink] = @DocLink, [DocStatus] = @DocStatus, [DateCreated] = @DateCreated, [DateUpdated] = @DateUpdated WHERE [DocID] = @DocID"><DeleteParameters><asp:Parameter Name="DocID" Type="Int32" /></DeleteParameters><InsertParameters><asp:Parameter Name="DocTitle" Type="String" /><asp:Parameter Name="DocBody" Type="String" /><asp:Parameter Name="DocLink" Type="String" /><asp:Parameter Name="DocStatus" Type="Int32" /><asp:Parameter Name="DateCreated" Type="DateTime" /><asp:Parameter Name="DateUpdated" Type="DateTime" /></InsertParameters><UpdateParameters><asp:Parameter Name="DocTitle" Type="String" /><asp:Parameter Name="DocBody" Type="String" /><asp:Parameter Name="DocLink" Type="String" /><asp:Parameter Name="DocStatus" Type="Int32" /><asp:Parameter Name="DateCreated" Type="DateTime" /><asp:Parameter Name="DateUpdated" Type="DateTime" /><asp:Parameter Name="DocID" Type="Int32" /></UpdateParameters></asp:SqlDataSource>
				</ContentTemplate>
			</cc1:TabPanel>
			<cc1:TabPanel runat="server" HeaderText="CarhireDocs" ID="TabPanel5">
				<HeaderTemplate>Carhire Docs
				</HeaderTemplate>
				<ContentTemplate><asp:GridView ID="CarhireDocs" CssClass="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" CellPadding="1" DataKeyNames="DocID" DataSourceID="CarhireDatasource" EmptyDataText="There are no data records to display." ForeColor="#333333" GridLines="None"><RowStyle BackColor="#EFF3FB" CssClass="RowStyle1" /><Columns><asp:CommandField ShowDeleteButton="True" ShowEditButton="True" ButtonType="Image" EditImageUrl="~/Images/Grid/IconEdit.png" DeleteImageUrl="~/Images/Grid/IconDelete.png" /><asp:BoundField DataField="DocID" HeaderText="ID" ReadOnly="True" SortExpression="DocID" /><asp:TemplateField HeaderText="Title" SortExpression="DocTitle"><EditItemTemplate><asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("DocTitle") %>'></asp:TextBox></EditItemTemplate><ItemTemplate><asp:HyperLink ID="ViewDocument" runat="server" NavigateUrl='<%# Eval("DocID", "ViewDocument.aspx?DocID={0}") %>' Text='<%# Eval("DocID") %>'></asp:HyperLink></ItemTemplate></asp:TemplateField><asp:BoundField DataField="DocStatus" HeaderText="Status" SortExpression="DocStatus" /><asp:BoundField DataField="DateCreated" HeaderText="Date Created" SortExpression="DateCreated" /><asp:BoundField DataField="DateUpdated" HeaderText="Date Updated" SortExpression="DateUpdated" /></Columns><EditRowStyle BackColor="#FDFDFD" /><FooterStyle CssClass="FooterStyle1" /><HeaderStyle CssClass="HeaderStyle1" /><PagerStyle CssClass="PagesStyle1" /><SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" /></asp:GridView><asp:SqlDataSource ID="CarhireDatasource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [Documents] WHERE [DocID] = @DocID" InsertCommand="INSERT INTO [Documents] ([DocTitle], [DocBody], [DocLink], [DocStatus], [DateCreated], [DateUpdated]) VALUES (@DocTitle, @DocBody, @DocLink, @DocStatus, @DateCreated, @DateUpdated)" ProviderName="<%$ ConnectionStrings:UC_LIVE.Properties.Settings.ConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [Documents] , [ClaimDoc] where ClaimDoc.ContactTypeID=4
and Documents.DocID = ClaimDoc.DocID" UpdateCommand="UPDATE [Documents] SET [DocTitle] = @DocTitle, [DocBody] = @DocBody, [DocLink] = @DocLink, [DocStatus] = @DocStatus, [DateCreated] = @DateCreated, [DateUpdated] = @DateUpdated WHERE [DocID] = @DocID"><DeleteParameters><asp:Parameter Name="DocID" Type="Int32" /></DeleteParameters><InsertParameters><asp:Parameter Name="DocTitle" Type="String" /><asp:Parameter Name="DocBody" Type="String" /><asp:Parameter Name="DocLink" Type="String" /><asp:Parameter Name="DocStatus" Type="Int32" /><asp:Parameter Name="DateCreated" Type="DateTime" /><asp:Parameter Name="DateUpdated" Type="DateTime" /></InsertParameters><UpdateParameters><asp:Parameter Name="DocTitle" Type="String" /><asp:Parameter Name="DocBody" Type="String" /><asp:Parameter Name="DocLink" Type="String" /><asp:Parameter Name="DocStatus" Type="Int32" /><asp:Parameter Name="DateCreated" Type="DateTime" /><asp:Parameter Name="DateUpdated" Type="DateTime" /><asp:Parameter Name="DocID" Type="Int32" /></UpdateParameters></asp:SqlDataSource>
				</ContentTemplate>
			</cc1:TabPanel>
			<cc1:TabPanel runat="server" HeaderText="Storage" ID="TabPanel6">
				<HeaderTemplate>Storage
				</HeaderTemplate>
				<ContentTemplate><asp:GridView ID="StorageGridView" CssClass="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" CellPadding="1" DataKeyNames="DocID" DataSourceID="StorageDatasource" EmptyDataText="There are no data records to display." ForeColor="#333333" GridLines="None"><Columns><asp:CommandField ShowDeleteButton="True" ShowEditButton="True" ButtonType="Image" EditImageUrl="~/Images/Grid/IconEdit.png" DeleteImageUrl="~/Images/Grid/IconDelete.png" /><asp:BoundField DataField="DocID" HeaderText="ID" ReadOnly="True" SortExpression="DocID" /><asp:TemplateField HeaderText="Title" SortExpression="DocTitle"><EditItemTemplate><asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("DocTitle") %>'></asp:TextBox></EditItemTemplate><ItemTemplate><asp:HyperLink ID="ViewDocument" runat="server" NavigateUrl='<%# Eval("DocID", "ViewDocument.aspx?DocID={0}") %>' Text='<%# Eval("DocID") %>'></asp:HyperLink></ItemTemplate></asp:TemplateField><asp:BoundField DataField="DocStatus" HeaderText="Status" SortExpression="DocStatus" /><asp:BoundField DataField="DateCreated" HeaderText="Date Created" SortExpression="DateCreated" /><asp:BoundField DataField="DateUpdated" HeaderText="Date Updated" SortExpression="DateUpdated" /></Columns><EditRowStyle BackColor="#FDFDFD" /><FooterStyle CssClass="FooterStyle1" /><HeaderStyle CssClass="HeaderStyle1" /><PagerStyle CssClass="PagesStyle1" /><RowStyle BackColor="#EFF3FB" CssClass="RowStyle1" /><SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" /></asp:GridView><asp:SqlDataSource ID="StorageDatasource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [Documents] WHERE [DocID] = @DocID" InsertCommand="INSERT INTO [Documents] ([DocTitle], [DocBody], [DocLink], [DocStatus], [DateCreated], [DateUpdated]) VALUES (@DocTitle, @DocBody, @DocLink, @DocStatus, @DateCreated, @DateUpdated)" ProviderName="<%$ ConnectionStrings:UC_LIVE.Properties.Settings.ConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [Documents] , [ClaimDoc] where ClaimDoc.ContactTypeID=5
and Documents.DocID = ClaimDoc.DocID" UpdateCommand="UPDATE [Documents] SET [DocTitle] = @DocTitle, [DocBody] = @DocBody, [DocLink] = @DocLink, [DocStatus] = @DocStatus, [DateCreated] = @DateCreated, [DateUpdated] = @DateUpdated WHERE [DocID] = @DocID"><DeleteParameters><asp:Parameter Name="DocID" Type="Int32" /></DeleteParameters><InsertParameters><asp:Parameter Name="DocTitle" Type="String" /><asp:Parameter Name="DocBody" Type="String" /><asp:Parameter Name="DocLink" Type="String" /><asp:Parameter Name="DocStatus" Type="Int32" /><asp:Parameter Name="DateCreated" Type="DateTime" /><asp:Parameter Name="DateUpdated" Type="DateTime" /></InsertParameters><UpdateParameters><asp:Parameter Name="DocTitle" Type="String" /><asp:Parameter Name="DocBody" Type="String" /><asp:Parameter Name="DocLink" Type="String" /><asp:Parameter Name="DocStatus" Type="Int32" /><asp:Parameter Name="DateCreated" Type="DateTime" /><asp:Parameter Name="DateUpdated" Type="DateTime" /><asp:Parameter Name="DocID" Type="Int32" /></UpdateParameters></asp:SqlDataSource>
				</ContentTemplate>
			</cc1:TabPanel>
		</cc1:TabContainer>
	</div>
</asp:Content>
